project:
  type: website
  output-dir: docs

website:
  title: "Tony JC Duan"

  navbar:

    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
  
      
    right:
      - text: "中文"
        href: https://www.bing.com

  page-footer:
    right: "This blog is built with ❤️ and [Quarto](https://quarto.org/)."
    
format:
  html:
    theme:   
      light: cosmo
      dark: darkly
    css: styles.css
    grid:
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem


resources:
  - "output_data/*"

filters:
  - foldableCodeBlcok.lua