project:
  type: website
  output-dir: docs

website:
  title: "Tony Jinchao Duan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - about cn.qmd
    right:
      - text: "中文"
        href: www.bing.com

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



